name: LeeesTpsMonitor
version: 1.0.0
main: Leees.tps.monitor.Main
api-version: 1.16
authors: [Nate, Legault]
description: tps monitor plugin
website: http://6b6t.org
commands:
  ltmreload:
    permission: ltm.admin
